name: Update Parent Issues on Comment

on:
  issue_comment:
    types: [created]

jobs:
  update-parent-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find Parent Issue References
        id: find_parents
        run: |
          PARENTS=$(gh issue view ${{ github.event.issue.number }} --json body --jq '.body | scan("Parents: #([0-9, ]+)") | .[0]')
          PARENT_ISSUE_NUMBERS=$(echo $PARENTS | tr ',' '\n' | tr -d ' ')
          echo "parent_issue_numbers=$PARENT_ISSUE_NUMBERS" >> $GITHUB_ENV

      - name: Get Top 5 Busiest Child Issues and Update Parents
        if: env.parent_issue_numbers != ''
        run: |
          for PARENT in ${{ env.parent_issue_numbers }}; do
            CHILD_ISSUES=$(gh issue list --json number,comments,title,html_url --search "Parents: #$PARENT" --jq 'sort_by(.comments) | reverse | .[:5]')
            TOP_ISSUES=$(echo "$CHILD_ISSUES" | jq -r '.[] | "- [#" + (.number|tostring) + "](" + .html_url + ") - " + .title + " (" + (.comments|tostring) + " comments)"')

            # Fetch the current description of the parent issue
            DESCRIPTION=$(gh issue view $PARENT --json body --jq '.body')

            # Check if the delimiters exist
            if echo "$DESCRIPTION" | grep -q "<!-- TOP_5_CHILD_ISSUES_START -->"; then
              # Replace the existing block between delimiters
              UPDATED_DESCRIPTION=$(echo "$DESCRIPTION" | sed -e "/<!-- TOP_5_CHILD_ISSUES_START -->/,/<!-- TOP_5_CHILD_ISSUES_END -->/c\\## Top 5 Busiest Child Issues\n<!-- TOP_5_CHILD_ISSUES_START -->\n$TOP_ISSUES\n<!-- TOP_5_CHILD_ISSUES_END -->")
            else
              # Append the new block if the delimiters do not exist
              UPDATED_DESCRIPTION="$DESCRIPTION\n\n## Top 5 Busiest Child Issues\n<!-- TOP_5_CHILD_ISSUES_START -->\n$TOP_ISSUES\n<!-- TOP_5_CHILD_ISSUES_END -->"
            fi

            # Update the parent issue description
            gh issue edit $PARENT --body "$UPDATED_DESCRIPTION"
          done
